# Generated by Django 5.1.1 on 2024-09-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='merch/images', verbose_name='Изображение'),
        ),
    ]
