# Generated by Django 5.1.1 on 2024-09-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='large_description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
    ]
