# Generated by Django 5.1.1 on 2024-09-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='video/previews', verbose_name='Путь к превью'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.ImageField(blank=True, upload_to='video/originals', verbose_name='Путь к видео'),
        ),
    ]
